config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => "homes#about"
  devise_for :users
  resources :books
  resources :users
  resources :post_images, only: [:new, :create, :index, :show, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum:2, maximum:20 }
  validates :introduction, length: { maximum:50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
     @user = current_user
     @books = Book.all
     @book = Book.new(book_params)
     @book.user_id = current_user.id
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end


  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
     redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "Book was successfully update."
    redirect_to book_path(@book.id)
   else
     @books = Book.all
     render :edit
   end
  end



  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
     redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
  end

  def index
    @post_images = PostImage.all
  end

  def show
    @post_image = PostImage.find(params[:id])
  end

  def destroy
    def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
    end
  end
  
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def create
      @book = Book.new(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to book_path(@book.id)
    else
     @books = Book.all
     redirect_to books_path
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
    flash[:notice] = "You have updated user successfully."
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
        <div class="error_explanation">
         <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
          <ul>
           <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
           <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@book,local:true do |f| %>
        <div>
          <p>Title<p>
          <%= f.text_field :title %>
        </div>
        <div>
          <P>Opinion</P>
          <%= f.text_area :body %>
        </div>

          <%= f.submit 'Update Book' , class:"btn btn-success" %>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: 'users/list',locals: {book: @book, user: @user } %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
     <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user,:profile_image, :fill, 100, 100, size:'100x100', fallback: "rails.png" %>
              <% end %>
            </td>
            <td>
              <span><%= link_to book.title, book_path(book.id) %></span>
            </td>
            <td>
              <span><%= book.body %></span>
            </td>
          </tr>
        <% end %>
      </tbody>
     </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: 'users/list',locals: {book: @book_new, user: @user } %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
  <tbody>
    <tr>
      <td>
        <%= link_to user_path(@user) do %>
          <%= attachment_image_tag @user,:profile_image, :fill, 100, 100, size:'100x100', fallback: "rails.png" %><br/>
          <%= @user.name %>
        <% end %>
      </td>
      <td><%= link_to @book.title, book_path(@book.id) %></td>
      <td><%= @book.body %></td>
      <% if @user == current_user %>
        <td><%= link_to 'Edit', edit_book_path(@book.id), class:"btn btn-success" %></td>
        <td><%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-danger" %></td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <h1>welcome to<i class="fas fa-book"></i> <strong>Bookers</strong> !!</h1>
      <p>In<strong>Bookers</strong></p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
     <div class="btn-wrapper col-10 mx-auto">
       <div class="row">
         <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block md-3 sign_in"%>
       </div>
       <div class="row">
         <%= link_to "Sign up", new_user_session_path, class:"btn btn-success btn-sm btn-block sign_up" %>
       </div>
     </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/f687367440.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: 'nav-link text-light' do %>
            Bookers
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'fas fa-home nav-link text-light' do %>
                    Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: 'fas fa-users nav-link text-light' do %>
                    Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to  books_path, class: 'fas fa-book-open nav-link text-light' do %>
                    Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' do %>
                    Log out
                  <% end %>
                </li>
            <% else %>
                <li>
                  <%= link_to root_path, class: "fas fa-home nav-link text-light" do %>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path, class: "fas fa-link nav-link text-light" do %>
                    About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "fas fa-user-plus nav-link text-light" do %>
                    Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" do %>
                    Log in
                  <% end %>
                </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="container">
            <p class="text-center">CopyRight Infratop.inc</p>
      </div>
    </footer>
  </body>
</html>

app/views/post_images/index.html.erb
<% @post_images.each do |post_image| %>
<div>
  <%= link_to post_image_path(post_image.id) do %>
  <%= attachment_image_tag post_image, :image %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag('sample-author1.jpg') %></p>
  <p>ユーザーネーム：<%= post_image.user.name %></p>
</div>
<% end %>

app/views/post_images/show.html.erb
<div>
  <%= attachment_image_tag @post_image, :image %>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
</div>

app/views/users/_list.html.erb
<% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <h2>User info</h2>
    <!-- if文から画像表示を入れるべき？　-->
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, size:'100x100', fallback: "rails.png" %>
    <table class="table">
      <tbody>
        <tr>
        </tr>
        <tr>
  	     <th>name</th>
  	     <th><%= user.name %></th>
       </tr>
       <tr>
  	     <th>introduction</th>
  	     <th><%= user.introduction %></th>
  	   </tr>
      </tbody>
    </table>
      <div class="row">
          <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <% if book.errors.any? %>
        <div class="error_explanation">
         <h2><%= book.errors.count %> errors prohibited this book from being saved:</h2>
          <ul>
           <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
           <% end %>
          </ul>
        </div>
      <% end %>
     <%= form_with model: book,local:true do |f| %>
      <div class="form-group">
         <h4>title</h4>
        <%= f.text_field :title %>
      </div>
      <div class="form-group">
         <h4>opinion</h4>
        <%= f.text_area :body %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book' , class:"btn btn-success" %>
      </div>
     <% end %>

app/views/users/edit.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div class="error_explanation">
         <h2><%= @user.errors.count %> errors prohibited this book from being saved:</h2>
          <ul>
           <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
           <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@user,local:true do |f| %>
        <div>
          <h4>name</h4>
          <%= f.text_field :name %>
        </div>
        <div>
          <h4>image</h4>
          <%= f.attachment_field :profile_image %>
        </div>
        <div>
          <h4>introduction</h4>
          <%= f.text_area :introduction %>
        </div>

        <%= f.submit 'Update User' , class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: 'users/list',locals: {book: @book, user: @user } %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, size:'100x100', fallback: "rails.png" %></td>
            <td><span><%= user.name %></span></td>
            <td><%=link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: 'users/list',locals: {book: @book, user: @user } %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user,:profile_image, :fill, 100, 100, size:'100x100', fallback: "rails.png" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>